### ISSUE TITLE
Error: unexpected '[' in facebook.php

### ISSUE THREAD

**Issue by Harielynn** [Benichou34/freesociallogin#1]
Hi!

I had a syntax error when I installed your module:

I have Prestashop 1.6.1.0 and PHP 5.3.14

```
Parse error: syntax error, unexpected '[', expecting ')' in modules/freesociallogin/facebook/facebook.php on line 232
[PrestaShop] Fatal error in module file modules/freesociallogin/facebook/facebook.php:
syntax error, unexpected '[', expecting ')'
```

is it related to my php version ?

thanks in advance!

**Comment by Benichou34** [comment]
Hello,

Yes, I think that your PHP version is too old. We use the Facebook and Google SDK, and both requires PHP 5.4 or greater.

Sorry for this inconvenience.
Regards

**Comment by Harielynn** [comment]
Yes it's PHP, I changed in 5.4.4 and now it works fine!
